Name: orders-api
NameWord: ordersapi
Package: org.example.performance
PackagePath: org/example/performance
ScalaVersion: 2.13.18
SbtVersion: 1.12.13
GatlingVersion: 3.13.5
SbtGatlingVersion: 4.18.3
SbtScalafmtVersion: 2.6.1
GatlingPicatinnyVersion: 1.17.1
BaseUrl: http://localhost
BaseAuthUrl: http://localhost/auth
WsBaseUrl: ws://localhost/ws
Intensity: 60 rpm
StagesNumber: "2"
RampDuration: 1 second
StageDuration: 1 second
TestDuration: 5 seconds
Pacing: 1 second
ScenarioName: Orders smoke flow
StartupBannerEnabled: "true"
DiagnosticsEnabled: "false"
KafkaPluginVersion: 1.0.6
KafkaStreamsVersion: 7.9.8-ce
JdbcPluginVersion: 1.0.3
AmqpPluginVersion: 1.2.10
