apiVersion: galaxio.io/v1
kind: TemplatePack
name: gatling
version: 0.12.1
description: Gatling performance testing templates
templates:
  - name: scala-sbt
    version: 0.2.0
    path: scala-sbt
    description: Gatling Scala project with sbt
  - name: java-maven
    version: 0.2.1
    path: java-maven
    description: Gatling Java project with Maven
  - name: kotlin-maven
    version: 0.2.1
    path: kotlin-maven
    description: Gatling Kotlin project with Maven
  - name: scala-gradle
    version: 0.2.1
    path: scala-gradle
    description: Gatling Scala project with Gradle
  - name: java-gradle
    version: 0.2.1
    path: java-gradle
    description: Gatling Java project with Gradle
  - name: kotlin-gradle
    version: 0.2.1
    path: kotlin-gradle
    description: Gatling Kotlin project with Gradle
